### ISSUE TITLE
Ignore specific directories

### ISSUE THREAD

**Issue by alexmigf** [StephaneBour/actions-php-lint#5]
Would be good to have a way to ignore specific directories from lint, for example like below:

```yml
- name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: '.'
          ignore: [ lib, test ]
```
